### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xGodly** [j0ach1mmall3/PermissionsShop#21]
Error occurred while enabling PermissionsShop v3.3.0 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.UI_BUTTON_CLICK
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.Sound.valueOf(Sound.java:1) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at com.j0ach1mmall3.permissionsshop.config.Config.<init>(Config.java:27) ~[?:?]
        at com.j0ach1mmall3.permissionsshop.Main.reload(Main.java:47) ~[?:?]
        at com.j0ach1mmall3.permissionsshop.Main.onEnable(Main.java:40) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**Comment by j0ach1mmall3** [comment]
Change the sounds to 1.8 ones
