### ISSUE TITLE
Plugin don't work

### ISSUE THREAD

**Issue by Ser3196** [j0ach1mmall3/PermissionsShop#4]
There is the console error: http://pastebin.com/P2nyqtpa
I have JLib and Vault installed

**Comment by Ser3196** [comment]
[10:33:13] [Server thread/INFO]: Starting minecraft server version 1.8.8
[10:33:13] [Server thread/INFO]: Loading properties
[10:33:13] [Server thread/INFO]: Default game type: SURVIVAL
[10:33:13] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-db6de12-d3e0b6f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[10:33:14] [Server thread/INFO]: Debug logging is disabled
[10:33:14] [Server thread/INFO]: Server Ping Player Sample Count: 12
[10:33:14] [Server thread/INFO]: Using 4 threads for Netty based IO
[10:33:14] [Server thread/INFO]: Generating keypair
[10:33:14] [Server thread/INFO]: Starting Minecraft server on 104.128.52.163:26413
[10:33:14] [Server thread/INFO]: Using epoll channel type 
[10:33:14] [Server thread/INFO]: Set PluginClassLoader as parallel capable

---

[10:33:14] [Server thread/ERROR]: Could not load 'plugins/PermissionsShop.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/j0ach1mmall3/permissionsshop/Main : Unsupported major.minor version 52.0
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
at java.lang.Thread.run(Thread.java:722) [?:1.7.0_03]
Caused by: java.lang.UnsupportedClassVersionError: com/j0ach1mmall3/permissionsshop/Main : Unsupported major.minor version 52.0
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_03]
at java.lang.ClassLoader.defineClass(ClassLoader.java:791) ~[?:1.7.0_03]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_03]
at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_03]
at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_03]
at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_03]
at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_03]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_03]
at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_03]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at java.lang.ClassLoader.loadClass(ClassLoader.java:423) ~[?:1.7.0_03]
at java.lang.ClassLoader.loadClass(ClassLoader.java:356) ~[?:1.7.0_03]
at java.lang.Class.forName0(Native Method) ~[?:1.7.0_03]
at java.lang.Class.forName(Class.java:264) ~[?:1.7.0_03]
at org.bukkit.plugin.java.PluginClassLoader.(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
... 6 more

**Comment by j0ach1mmall3** [comment]
Install java 8
